### ISSUE TITLE
How to determine TSmart power

### ISSUE THREAD

**Issue by BettySwallocks** [pdw-mb/tsmart_ha#3]
First - thanks for building on the BritKat MQTT solution for TSmart and enabling a simpler Python & HACS enabled integration.  When I used the MQTT original I was able to pick up a numeric power attribute and use it in a Riemann Sum Integral helper for my Engergy dashboard.  Your new integration doesn't seem to expose that power value, unless I've just missed it somewhere?  Do you plan to add something to your system as I assume this is there in the TSmart API?

**Comment by pdw-mb** [comment]
The device doesn't know the power of the heating element that it's attached to.  As of yesterday, the integration exposes the state of the power relay as a binary sensor, so it should be possible to convert that to a numeric value (probably using a template sensor) and then integrate that.  I've not tried this myself, but it's on my list to do.

I've not tried the MQTT solution, but I assume that that is letting you set the power and then returning that as the power when the relay is on.

**Comment by BettySwallocks** [comment]
Yeah that makes sense, the MQTT knows the immersion is using 3000W when 'on' so it probably just uses the active time of the relay and a dumb calculation. Very much appreciated if you want to add something in - otherwise I'll set up a calculation of my own (eventually).

**Comment by pdw-mb** [comment]
Does the MQTT solution let you set the heater power, or just assume that it's 3kW?  It'd be pretty easy to add if we assume the heater is 3kW, but pretty awkward to add if we want to make it configurable.

I think 3kW is pretty standard for immersion heaters.

@holdestmade mentioned as a solution PowerCalc for deriving power from the relay state, but I've not tried it.

**Comment by BettySwallocks** [comment]
I didn't know much about Powercalc, but I'm happy to give that a try to avoid adding unecessary fixed values into the new Python code.

**Comment by paulwarren-wk** [comment]
The following template sensor will convert the relay state into a numerical power value

```yaml
sensor:
  - platform: template
    sensors:
        immersion_heater_power:
            friendly_name: "Immersion heater power (kW)"
            unit_of_measurement: "kW"
            value_template: "{{ 3 if is_state('binary_sensor.MY_HEATER_relay', 'on') else 0 }}"
```

This can then be integrated to get consumption.

**Comment by pdw-mb** [comment]
The following template sensor will convert the relay state into a numerical power value:

```yaml
sensor:
  - platform: template
    sensors:
        immersion_heater_power:
            friendly_name: "Immersion heater power (kW)"
            unit_of_measurement: "kW"
            value_template: "{{ 3 if is_state('binary_sensor.MY_HEATER_relay', 'on') else 0 }}"
```

This can then be integrated to get consumption.
